server:
  port: ${SERVER.PORT:8080}
  servlet:
    context-path: ${CONTEXT.PATH:/}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    com:
      general:
        interceptor: DEBUG
        feign: DEBUG
      zaxxer:
        hikari: debug
        hikari.HikariConfig: DEBUG
      netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
    me.coong: debug
spring:
  application:
    name: shop
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12779955?useSSL=false&serverTimezone=UTC
    username: sql12779955
    password: IdAUgV6d5v
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 30000
      connection-test-query: select 1
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    log-resolved-exception: true
